### ISSUE TITLE
Revision Task List

### ISSUE THREAD

**Issue by sullivannicole** [sullivannicole/nuestro-iowa#21]
Per Joel, 2021-08-26:

- [x] The bullet points on tab 1 seem to have a rendering problem
- [x] Could you make sure all y-axes are set to zero? I was amazed at some of the change that happened over time, but then realized it was the scale.
- [x] On some plots, you could remove the x-axis labels. Particularly, the time series plots labeled "year" can be removed. It overlaps with the values and isn't really needed.

**Comment by sullivannicole** [comment]
Per Joel and Darcie, 2021-09-09:
**Tab 1**
- [x] Drop in mission/vision
- [x] Remove sponsor pictures

**Tab 2**
- [x] Basemap on tab 2 needs larger text
- [x] Title on map legend to read 'people or %'
- [x] Button on map -> change "raw number" to "# of Latinx people"
- [x] Employment plot -> should have 16 to 64 pop only
- [x] Poverty plot -> "Living in poverty" and make it clear that "incomes" are below fed poverty level in text description

**Tab 3**
- [x] Change pink to green hex
- [x] Employment -> needs to be 16 to 64 pop

**Comment by sullivannicole** [comment]
After workshop:

**Sidebar**
- [x] Caption logo with "our Iowa" (or hover over)

**Tab 1**
- [x] "Nuestra vision" instead of "nuestro vision"
- [x] Add a synopsis of what the project is
- [x] Remove "nuestros leaders" on down
- [x] Switch cards to flip cards. Back side will include Spanish translation
- [x] Add mission statement. Under "deep dive": "in this dashboard you'll find..."; what can you do by exploring the db? Bonus points if a journalist or Dawn could copy/paste the text. "Our contributions to the state make us essential to Iowa's future"

**Tab 2**
- [x] Put zipcodes on map
- [x] Caption that says you can click on dropdown arrow map
- [x] Consistency with same features across charts (color, MOEs, etc.)
- [x] Change insurance plot to proportions of each group with/without insurance

**Tab 3**
- [x] Keep races same color throughout
- [ ] ~Add note on homeownership plot: 'doesn't take into account home value'~


**Tab 4**
- [x] Reformat the page so all the inputs show up in a bar on the left; all the outputs change interactively on the right; education investments & citizenship policy headers
- [ ] ~~Call out adult education potential~~
- [ ] Include info icon with hover-over with "How do I choose my inputs?". "Choose based on concrete work, e.g. # of scholarships given over the next 10 years" **TBD if we need**
- [x] Add reference bars to plots (put number text on plot) so change is clearly visible
- [x] Sum of additional earnings over time (as a #) included somewhere. TurboTax type of interface

**Comment by sullivannicole** [comment]
- [ ] Drop Spanish translations onto cards on Tab 1

**Comment by sullivannicole** [comment]
- [x] Remove all MOEs from plot on **nuestro county** tab (tab 2)
